spring:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://localhost:5432/soft_delete
      driver-class-name: org.postgresql.Driver
      username: user
      password: pass
    jpa:
        hibernate:
            ddl-auto: none
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE